import Link from "next/link";
import {usePathname} from "next/navigation";
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
const navLinks=[
  {name: "Register ", href:"/register"},
  {name: "login ", href:"/login"},
  {name: "forgetPassword ", href:"/ForgotPassword"}
]
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div>
      {navLinks.map((link)=>{
        return(
          <Link href ={link.href} key={link.name}>
            {link.name}
          </Link>
        )
      })}
    </div>
  )
}
