'use client'
import Link from "next/link";
import {usePathname} from "next/navigation";
// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }
import { useState } from "react";
const navLinks=[
  {name: "Register ", href:"/register"},
  {name: "login ", href:"/login"},
  {name: "forgetPassword ", href:"/forgot-password"}
]
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const pathname = usePathname()
 const [input,setInput] = useState("")

  return (
    <div>
      <div>
        <input value={input} onChange={e =>setInput(e.target.value)}></input>
      </div>
      {navLinks.map((link)=>{
         const isActive = pathname.startsWith(link.href);
        return(
          <Link href ={link.href} key={link.name}
           className={isActive?"font-bold mr-5":"text-blue-500"}>
            {link.name}
          </Link>
        )
      })}
      {children}
    </div>
  )
    
}
